### ISSUE TITLE
Hosted version down?

### ISSUE THREAD

**Issue by mnoorenberghe** [DeMille/url-cast-receiver#1]
I get a Google error page with a 404 showing the URL `/host/0B82…` when I try to launch the hosted app. Is the app still registered with Google and working for you?

**Comment by DeMille** [comment]
Yeah you're right. I had it hosted on gdrive, but they just ended support for html hosting. Must have ignored the warning email like a year ago!

It's hosted on a github page now so its back up :)

**Comment by ghost** [comment]
Is anyone going to close this?

**Comment by DeMille** [comment]
Doh, yes, I should close this. Should still be working.
