### ISSUE TITLE
3 years after

### ISSUE THREAD

**Issue by PrincesseLulu** [DeMille/url-cast-receiver#3]
This is always fonctional ?
I'have a white screen :/

**Comment by CobraCalle** [comment]
me too... is it possible, google started blocking iframes in web receivers?

**Comment by cashpipeplusplus** [comment]
See https://github.com/DeMille/url-cast-receiver/issues/5#issuecomment-719774071

https://www.google.com/, for example, will not allow itself to be loaded into an iframe.

**Comment by CobraCalle** [comment]
you are right... it is still working... thank you very much
